export {default as PlansTop} from './PlansHead'
export {default as AddWeeklyTariffPlanModal} from './AddWeeklyTariffPlan'
export {default as AddEventsModal} from './AddEventsModal'
export {default as WeeklyPlansTable} from './WeeklyPlans'
export {default as SpecialOccassionsTable} from './SpecialOccassion'
export {default as OccupancyManagerTable} from './OccupancyManager'